### ISSUE TITLE
Pipeline setup not working as intended

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastcore#141]
The setup is not chaining the encodes and subsequent setups of the pipeline.
```python
class A(Transform):
    def setups(self, x):
        print(f'A: {x}')
    def encodes(self, x): return 'a'
    
class B(Transform):
    def setups(self, x):
        print(f'B: {x}')
    def encodes(self, x): return 'b'

pipe = Pipeline([A,B])

pipe.setup(1)
>> A: 1
   B: 1
```

**Comment by tcapelle** [comment]
I can make a pull request to fix this, probably modifying the `setup` method on the class `Pipeline` to something like this:

```python
def setup(self, items=None, train_setup=
  tfms = self.
  self.fs.
   for t in tfms: 
    self.add(t,items, train_setup)
    items = t(items)
```

**Comment by jph00** [comment]
I'm not sure there's a way to make this work without breaking existing functionality. I'll close this issue, since it's not what's currently designed, but if you or anyone comes up with a PR that makes this work whilst keeping everything else working too (and isn't much slower than now) I'd be happy to take a look.
