### ISSUE TITLE
removal of `map_filter`: breaks nbdev and is still referenced in fastcore docs.

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastcore#164]
map_filter was removed in https://github.com/fastai/fastcore/commit/e72fe807d0822206e947be1fb015e7691e2a63c3

This caused the following problems:

- The docs still reference `map_filter`
- nbdev had a dependency on `map_filter`
- docs are not being built for fastcore https://github.com/fastai/fastcore/runs/1337539063?check_suite_focus=true#step:4:27

I looked at the change and it isn't immediately obvious to me why `map_filter` was removed - so I am not sure what the desired fix is here.  I'm happy to fix it but want to check with you first to get more context. 

@jph00

**Comment by hamelsmu** [comment]
Related issue: https://github.com/fastai/nbdev/issues/299

**Comment by hamelsmu** [comment]
Nevermind I found the answer in the release notes

> Redundent L.map_filter removed (since L.map.filter does the same thing)

**Comment by jph00** [comment]
Looks like I forgot to make the nbdev release. It's happening now. Thanks for letting me know.

**Comment by ZivotJeKrasny** [comment]
I think the correct solution would be to upgrade major version of `fastcore` to 2.0 because there is a major incompatibility in it's API. Or provide some backwards compatibility such as alias `L.map_filter = L.map.filter`  and create new release `1.3.2` ;) 

NBDev is only of of many project which are using this library so this can cause a lot of problems in the world ;)

**Comment by hamelsmu** [comment]
Looks like this is fixed by https://github.com/fastai/nbdev/commit/fd4cfac2a85875e9b6f9dad3012b34fc9e8a6a67
